import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const C=require('../app/src/main/assets/consumables.js');
const elements=new Map(),alerts=[],prompts=[];
const element=id=>{if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',dataset:{},classList:{add(){},remove(){}}});return elements.get(id)};
let tile=null;
const parent={classList:{add(){}}};
const available={textContent:'AVAILABLE WORKERS',parentElement:parent,closest(){return this},insertAdjacentElement(position,card){tile=card}};
const host={querySelector(){return tile},querySelectorAll(selector){return selector.startsWith('.cons-launch')?[]:[available]}};
const state={jobs:[{no:'JC1',vehicle:'Toyota Camry',make:'Toyota',model:'Camry',year:2020,reg:'REG1',status:'Open'},{no:'JC2',vehicle:'Lexus LX',make:'Lexus',model:'LX',year:2021,reg:'REG2',status:'Open'},{no:'ID001'}],assign:[{job:'JC1',emp:'P1',assignedBy:'S1'}]};
const ctx={state,users:[{id:'P1',name:'Painter',department:'Painter'},{id:'S1',name:'Supervisor',role:'Supervisor'}],me:{id:'M1',role:'Manager'},ZukaitConsumables:C,console,
 document:{head:{appendChild(){}},createElement(){return {}},getElementById(id){if(id==='supervisorView')return host;if(id==='managerView')return null;return element(id)},querySelectorAll(selector){if(selector==='.cons-search-tabs button'||selector==='.cons-price-choice button')return [];return element('consActualRows').innerHTML.match(/value="([^"]*)"/g)?.map(x=>({value:x.slice(7,-1)}))||[]}},
 alert:x=>alerts.push(x),prompt:()=>prompts.length?prompts.shift():'Verified correction',confirm:()=>true,setTimeout:fn=>fn(),render(){},save(){ctx.saved=JSON.stringify(state)},closeModal(){},openModal(html){ctx.modal=html}};
ctx.window=ctx;vm.createContext(ctx);
vm.runInContext('let me=window.me; delete window.me;',ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/consumables_ui.js','utf8'),ctx);
const fill=values=>Object.entries(values).forEach(([id,value])=>element(id).value=value);
fill({cmMaterial:'Primer',cmBrand:'Brand',cmUnit:'Liter',cmPrice:'3.5',cmDate:'2020-01-01'});
ctx.consSaveMaster();assert.equal(state.consumables.materials.length,1);assert.equal(state.consumables.brands.length,1);assert.match(element('cmList').innerHTML,/OMR 3.500/);assert.doesNotMatch(element('cmList').innerHTML,/NaN/);
const m=state.consumables.materials[0],b=state.consumables.brands[0];
vm.runInContext("me={id:'S1',role:'Supervisor'}",ctx);ctx.render();assert.equal(tile.className,'cons-supervisor-tile');ctx.render();assert.ok(tile);
ctx.openConsumablesEntry('issued');fill({consJc:'REG1'});ctx.consFindJC('issued');assert.match(element('consJcResults').innerHTML,/JC1/);assert.match(element('consJcResults').innerHTML,/REG1/);ctx.consSelectJC('JC1');assert.match(element('consVehicleDetails').innerHTML,/Toyota Camry/);assert.match(element('consVehicleDetails').innerHTML,/REG1/);assert.match(element('consVehicleDetails').innerHTML,/2020/);
assert.equal(element('consFinishBtn').disabled,true,'FINISH must remain disabled before a material line is added');
ctx.openConsumablesEntry('issued');fill({consJc:'JC1'});ctx.consLoadJC('issued');fill({consMaterial:m.id,consBrand:b.id,consQty:'2',consPainter:'P1',consColour:'040'});ctx.consAddLine();assert.equal(element('consFinishBtn').disabled,false,'FINISH must enable after valid JC, painter and material line');ctx.consFinishIssue();
assert.equal(state.consumables.issues.length,1);
ctx.openConsumablesEntry('additional');assert.match(ctx.modal,/consAdditionalWorkspace/);assert.doesNotMatch(ctx.modal,/id="consPainter"/);assert.doesNotMatch(ctx.modal,/id="consColour"/);fill({consJc:''});ctx.consFindJC('additional',true);assert.match(element('consJcResults').innerHTML,/JC1/);assert.doesNotMatch(element('consJcResults').innerHTML,/JC2/);ctx.consSelectJC('JC1');assert.match(element('consAdditionalContext').innerHTML,/ADDING EXTRA MATERIALS TO JC JC1/);assert.match(element('consAdditionalContext').innerHTML,/Painter/);fill({consMaterial:m.id,consBrand:b.id,consQty:'0.5'});ctx.consAddLine();assert.equal(element('consFinishBtn').disabled,false,'Additional FINISH must enable without re-entering painter/supervisor/colour');ctx.consFinishIssue();
assert.equal(state.consumables.issues.length,2);const additional=state.consumables.issues.find(x=>x.type===C.TYPES.ADDITIONAL);assert.ok(additional);assert.equal(additional.mainPainterId,'P1');assert.equal(additional.allottedSupervisorId,'S1');assert.equal(additional.colourCode,'040');
ctx.openConsumablesActual();fill({consActualJc:'JC1'});ctx.consLoadActual();assert.match(element('consActualRows').innerHTML,/Primer/);assert.match(element('consActualRows').innerHTML,/max="2.5"/);assert.match(element('consActualRows').innerHTML,/value="2.5"/);
element('consActualRows').innerHTML=element('consActualRows').innerHTML.replace('value="2.5"','value="2.25"');ctx.consFinishActual();assert.equal(state.consumables.actuals.length,0);assert.match(ctx.modal,/FINAL CHECK BEFORE LOCKING/);assert.match(ctx.modal,/OMR 7.875/);ctx.consConfirmFinishActual();assert.equal(state.consumables.actuals.length,1);assert.equal(state.consumables.actuals[0].totalCost,7.875);assert.equal(state.consumables.actuals[0].createdBy,'S1');
fill({consSearchJc:'JC1'});ctx.consShowSearch();let searchHtml=element('consSearchResult').innerHTML;
assert.match(searchHtml,/SUGGESTED \/ ISSUED/);assert.match(searchHtml,/2.5 Liter/);assert.match(searchHtml,/Price \(OMR\)/);assert.match(searchHtml,/Material Cost \(OMR\)/);assert.match(searchHtml,/8\.750/,'Suggested / Issued must calculate material cost from current price');assert.match(searchHtml,/Total Material Cost \(OMR\)/);assert.doesNotMatch(searchHtml,/Based on current material price/);assert.doesNotMatch(searchHtml,/Actual Quantity/);assert.doesNotMatch(searchHtml,/Approx\./);
ctx.consSetSearchView('actual');ctx.consShowSearch();searchHtml=element('consSearchResult').innerHTML;
assert.match(searchHtml,/ACTUAL MATERIALS/);assert.match(searchHtml,/Actual Quantity/);assert.match(searchHtml,/Actual Cost \(OMR\)/);assert.match(searchHtml,/2.25 Liter/);assert.match(searchHtml,/7\.875/,'Actual Materials must show finalized actual cost');assert.match(searchHtml,/Total Material Cost \(OMR\)/);assert.doesNotMatch(searchHtml,/Based on current material price/);assert.doesNotMatch(searchHtml,/Approx\./);assert.doesNotMatch(searchHtml,/\[object Object\]|undefined/);
vm.runInContext("me={id:'M1',role:'Manager'}",ctx);ctx.consRunReports();assert.match(element('crResult').innerHTML,/2.25 Liter/);assert.match(element('crResult').innerHTML,/OMR 7.875/);
fill({csmMaterial:m.id});ctx.consMaterialHistory();assert.match(element('csmResult').innerHTML,/OMR 3.500/);assert.doesNotMatch(element('csmResult').innerHTML,/NaN/);
assert.match(element('cmList').innerHTML,/EDIT PRICE/);const currentPrice=state.consumables.prices.find(x=>x.materialId===m.id&&x.brandId===b.id&&!x.voided);prompts.push('4.250','Correct current master price');ctx.consEditMasterPrice(currentPrice.id);assert.match(element('cmList').innerHTML,/OMR 4.250/);assert.equal(state.consumables.actuals[0].totalCost,7.875);assert.ok(state.consumables.audit.some(x=>x.type==='PRICE_CORRECTED'&&x.entityId===currentPrice.id));
const before=JSON.stringify(state);prompts.push(null);assert.doesNotThrow(()=>ctx.consHistoryCorrectActual(state.consumables.actuals[0].id));assert.equal(JSON.stringify(state),before);
assert.throws(()=>C.managerCorrectActual(state,state.consumables.actuals[0].id,[{materialId:m.id,brandId:b.id,quantity:1}],vm.runInContext('me',ctx),''),/REASON_REQUIRED/);assert.equal(JSON.stringify(state),before);
assert.throws(()=>C.managerCorrectIssue(state,state.consumables.issues[0].id,{colourCode:'changed'},vm.runInContext('me',ctx),''),/REASON_REQUIRED/);assert.equal(JSON.stringify(state),before);
fill({consActualJc:'bad'});ctx.consLoadActual();assert.equal(element('consActualVehicle').value,'');
ctx.openConsumablesModule();assert.match(ctx.modal,/disabled[^>]*><span>🛠️/);
const hm={id:'legacy-mat',name:'Legacy Reducer',unit:'Liter',category:'Consumable',active:true},hb={id:'legacy-brand',name:'Legacy Brand',active:true},hi={id:'legacy-issue',type:C.TYPES.ISSUED,jobCard:'OLD-JC',voided:false,createdAt:1,lines:[{materialId:hm.id,brandId:hb.id,quantity:1}]};state.consumables.materials.push(hm);state.consumables.brands.push(hb);state.consumables.issues.push(hi);ctx.openConsumablesEntry('issued');fill({consMaterialSearch:'Legacy Reducer'});ctx.consSearchMaterialBrand();assert.match(element('consMaterialResults').innerHTML,/Legacy Reducer/,'historically used material must remain searchable even without a current price row');assert.match(element('consMaterialResults').innerHTML,/Legacy Brand/);state.consumables.issues.pop();state.consumables.brands.pop();state.consumables.materials.pop();
const uiSource=fs.readFileSync('app/src/main/assets/consumables_ui.js','utf8');
assert.match(uiSource,/Price on Print \/ PDF/,'Search Material print area must expose price visibility choice');
assert.match(uiSource,/WITH PRICE/);assert.match(uiSource,/WITHOUT PRICE/);
assert.match(uiSource,/consSearchView='issued'/,'Search Material must default to Suggested / Issued view');
assert.match(uiSource,/SUGGESTED \/ ISSUED/);assert.match(uiSource,/ACTUAL MATERIALS/);
assert.match(uiSource,/Price \(OMR\)/);assert.match(uiSource,/Material Cost \(OMR\)/);assert.match(uiSource,/Actual Cost \(OMR\)/);
assert.match(uiSource,/Total Material Cost \(OMR\)/);assert.doesNotMatch(uiSource,/Based on current material price/);assert.match(uiSource,/MATERIAL COST/);
assert.match(uiSource,/consPrintPriceMode==='without'/,'print authority must support without-price mode');
assert.match(uiSource,/\.cons-price-col,\.cons-list-total,\.cons-price-note,\.cons-cost-label/,'WITHOUT PRICE must strip price columns, totals and costing labels');
assert.doesNotMatch(uiSource,/PRINT \/ PDF BOTH/,'combined Suggested + Actual print must not return');
assert.doesNotMatch(uiSource,/Approx\./,'Search Material UI must not use Approx wording');
assert.match(uiSource,/name="viewport" content="width=device-width,initial-scale=1"/,'print preview must be mobile responsive');
assert.match(uiSource,/cons-entry-line-cards/,'Suggested / Issued entry must use responsive material cards');
assert.match(uiSource,/cons-actual-line-cards/,'Actual Materials entry must use responsive cards');
assert.match(uiSource,/TOTAL ISSUED/,'Actual material cards must keep the issued allowance visible');
assert.match(uiSource,/ACTUAL QTY/,'Actual material cards must keep the editable actual quantity');
assert.match(uiSource,/consStripSearchActions/,'print/share must operate on the selected list only');
assert.match(uiSource,/\.cons-summary\{display:grid/,'print preview must preserve structured summary layout');
assert.ok(ctx.saved);assert.ok(!alerts.includes('MANAGER_ONLY'));console.log('Consumables UI integration tests passed: Job Card picker/vehicle details, simplified Additional Materials inheritance, duplicate safeguards, final Actual review, actor audit, search, reports, manager price editing and supervisor tile');

