import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const clickHandlers=[],styles=[];let modal='';
const start=Date.parse('2026-10-03T04:00:00Z');
const st={jobs:[{no:'12037',vehicle:'Toyota Corolla',reg:'1234 AB',year:2020,jobType:'CASH',amount:100,delivered:true,deliveredAt:start,finalInvoiceAmount:95,financialAudit:[{operation:'FINAL_INVOICE_CORRECTION',from:100,to:95,reason:'Customer adjustment',at:start}]}],assign:[{id:'a',job:'12037',emp:'E1',suggested:60,completed:true}],sessions:[{id:'s',job:'12037',emp:'E1',start,end:start+3600000}],consumables:{materials:[{id:'m1',name:'Sanding Disc'},{id:'m2',name:'Polish'}],brands:[{id:'b',name:'3M'}],issues:[{jobCard:'12037',locked:true,department:'Painting',lines:[{materialId:'m1',brandId:'b',unit:'piece',quantity:10}]}],actuals:[{jobCard:'12037',department:'Painting',locked:true,actualAt:start,totalCost:10,lines:[{materialId:'m1',brandId:'b',unit:'piece',actualQuantity:10,unitPriceSnapshot:1,lineCost:10}]},{jobCard:'12037',department:'Denting',locked:true,actualAt:start+1,totalCost:25,lines:[{materialId:'m2',brandId:'b',unit:'L',actualQuantity:5,unitPriceSnapshot:5,lineCost:25}]},{jobCard:'12037',locked:true,voided:true,totalCost:999,lines:[{materialId:'VOIDED'}]},{jobCard:'12037',locked:false,totalCost:999,lines:[{materialId:'DRAFT'}]},{jobCard:'OTHER',locked:true,totalCost:999,lines:[{materialId:'OTHER'}]}]},paintPurchasing:{orders:[{jobCard:'12037',poNumber:'PO001',vendor:'Vendor',receivedAt:start,colorCode:'040',lines:[{id:'p',paintType:'Basecoat',quantity:2,pricePerLitre:5,lineTotal:10}],returns:[{lineId:'p',paintType:'Basecoat',quantity:0.5,value:2.5,reason:'Excess paint'}]}]},paintCosting:{'12037':{netPaintCost:7.5}},labourRate:2.5};
const staff=[{id:'E1',name:'Surab',department:'Painter'}];
const sandbox={fixture:st,staff,window:{openModal:html=>modal=html,closeModal(){},zukaitV2:{sparePartsMain:{reportRows:()=>[{jobCard:'12037',part:'Bumper',qty:1,status:'RECEIVED',amount:20},{jobCard:'12037',part:'Clip',qty:1,status:'ORDERED',amount:7}],listsForJobCard:()=>[]}}},document:{addEventListener:(type,fn)=>{if(type==='click')clickHandlers.push(fn)},createElement:()=>({}),head:{appendChild:s=>styles.push(s.textContent)},body:{},getElementById:()=>null,querySelector:()=>null},navigator:{onLine:true},MutationObserver:class{observe(){}},setTimeout(){},setInterval(){},totalForAssignment:()=>60};
const ctx=vm.createContext(sandbox);vm.runInContext('let state=fixture;let users=staff;let me={role:"Manager"};',ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/paint_order_rules.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/job_cost_summary_v128.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/workshop_overview.js','utf8'),ctx);
const click=(action)=>{for(const handler of clickHandlers)handler({target:{closest:selector=>selector.includes('=')&&selector!=='[data-workshop-action="'+action+'"]'?null:({dataset:{workshopAction:action,job:'12037'}})},preventDefault(){},stopPropagation(){}})};
sandbox.window.zukaitWorkshopOverview.detail('12037');
assert.ok(modal.includes('workshop-overview wo-360-page'),'overview must receive its intended full-page styles');
assert.ok(modal.includes('data-workshop-action="print-360"'),'PDF controls must be present on overview');
assert.ok(modal.includes('data-workshop-action="search"'),'overview back goes to search');
assert.ok(!modal.includes('Authoritative Job Card'));assert.ok(!modal.includes('All labour, consumables'));
assert.ok(!modal.includes('Tap any cost box'));
assert.ok(modal.includes('OMR 35.000'));
assert.ok(modal.includes('class="wo-job-banner"'),'sample navy identity banner is present');
for(const type of ['parts','consumables','paint','labour','total','invoice'])assert.ok(modal.includes('data-workshop-action="cost-'+type+'"'));
for(const cls of ['tech','parts','timeline','audit'])assert.ok(modal.includes('<details class="wo-360-card wo-360-'+cls+'-card">'));
assert.ok(modal.includes('<summary>Financial History</summary>'));
click('cost-consumables');
for(const value of ['Sanding Disc','Polish','3M','10 piece','5 L','OMR 35.000','OMR 10.000','OMR 25.000','Suggested / Issued'])assert.ok(modal.includes(value),value);
for(const excluded of ['VOIDED','DRAFT','OTHER','999.000'])assert.ok(!modal.includes(excluded));
assert.ok(modal.includes('data-workshop-action="detail"'),'drilldown back restores overview');
click('detail');assert.ok(modal.includes('Job Card & Vehicle'));
click('cost-paint');for(const value of ['Basecoat','PO001','040','Returns','Excess paint','OMR 7.500','OMR 2.500'])assert.ok(modal.includes(value),value);
click('cost-parts');assert.ok(modal.includes('Bumper'));assert.ok(modal.includes('Charged Purchase · OMR 20.000'));assert.ok(modal.includes('Pending'));
click('cost-labour');assert.ok(modal.includes('Surab'));assert.ok(modal.includes('OMR 2.500'));
click('cost-total');assert.ok(modal.includes('OMR 65.000'));for(const type of ['parts','consumables','paint','labour'])assert.ok(modal.includes('data-workshop-action="cost-'+type+'"'));
click('cost-materials-paint');assert.ok(modal.includes('OMR 42.500'));assert.ok(modal.includes('cost-consumables'));assert.ok(modal.includes('cost-paint'));
click('cost-invoice');assert.ok(modal.includes('OMR 95.000'));assert.ok(!modal.includes('not a separate'));
vm.runInContext('me={role:"Supervisor"}',ctx);click('detail');assert.ok(modal.includes('wo-360-page'));
vm.runInContext('me={role:"Employee"}',ctx);const prior=modal;click('cost-consumables');assert.equal(modal,prior);
assert.ok(styles.join('').includes('[data-workshop-action="cost-consumables"]'));
fs.writeFileSync(path.join(os.tmpdir(),'zukait-job360-preview.html'),modal);
console.log('360 view: styled overview, all department consumables, itemized paint/returns, nested expense drilldowns, invoice, back navigation and role guards passed');
