-- Apply both pending Phase 2 migrations in this transaction, then ROLLBACK.
-- All fixture numbers are inserted explicitly; no RC/estimate nextval calls.
do $$
declare
 mgr text; sup text; emp text; ins bigint; rc text:='RC-QA-APP-'||gen_random_uuid();
 eid text:=gen_random_uuid()::text; eno text:='Zi-QA-'||gen_random_uuid();
 source_state jsonb; source_revision bigint; source_parts bigint; source_events bigint;
 rc_seq bigint; rc_called boolean; est_seq bigint; est_called boolean;
 e jsonb; item jsonb; c jsonb; link_cmd jsonb; a jsonb; b jsonb; qid uuid; ref_cmd jsonb; parts jsonb;
begin
 select user_id into mgr from staff_credentials where role='Manager' and active limit 1;
 select user_id into sup from staff_credentials where role='Supervisor' and active limit 1;
 select user_id into emp from staff_credentials where role='Employee' and active and not exists(select 1 from workshop_reception_access a where a.user_id=staff_credentials.user_id and a.active) limit 1;
 select id into ins from workshop_insurance_companies where active limit 1;
 if mgr is null or sup is null or emp is null then raise exception 'test actors unavailable'; end if;
 select data,revision into source_state,source_revision from workshop_state where id='main' for update;
 select count(*) into source_parts from workshop_v2_spare_part_state;
 select count(*) into source_events from workshop_v2_events;
 select last_value,is_called into rc_seq,rc_called from workshop_reception_no_seq;
 select last_value,is_called into est_seq,est_called from workshop_v2_estimate_no_seq;
 if has_table_privilege('anon','workshop_reception_estimates','select') or has_table_privilege('authenticated','workshop_reception_approvals','select') or has_table_privilege('service_role','workshop_reception_approvals','update') or has_table_privilege('service_role','workshop_reception_approvals','delete') then raise exception 'invalid grants'; end if;
 if exists(select 1 from pg_class where oid in ('workshop_reception_estimates'::regclass,'workshop_reception_approvals'::regclass) and not relrowsecurity) then raise exception 'RLS not enabled'; end if;
 if has_function_privilege('anon','zukait_reception_identity(jsonb,bigint)','execute') or has_function_privilege('authenticated','zukait_reception_command(text,jsonb)','execute') then raise exception 'exposed RPC'; end if;
 insert into workshop_receptions(rc_no,sequence_no,insurance_id,details,location,created_by,updated_by) values(rc,-90001,ins,'{"make":"Toyota","model":"Camry","registration":"QA-1"}','VWC',mgr,mgr),(rc||'-other',-90002,ins,'{"make":"Toyota","model":"Camry","registration":"QA-1"}','VWC',mgr,mgr);
 item:=jsonb_build_object('id',gen_random_uuid(),'name','Front bumper','part_no','B1','qty',2);
 parts:=jsonb_build_array(item);
 insert into workshop_reception_preliminary_parts(rc_no,items,updated_by) values(rc,parts,mgr);
 insert into workshop_v2_estimate_numbers(estimate_no,sequence_no,client_key,created_by) values(eno,-90001,eid,mgr);
 e:=jsonb_build_object('id',eid,'estimateNo',eno,'makeModel','Toyota Camry','registration','QA-1','jobCard','','type','LS','lsRows',jsonb_build_array(jsonb_build_object('description','Repair','amount',120.555)),'vatEnabled',true,'updatedAt',1);
 update workshop_state set data=jsonb_set(source_state,'{estimates}',coalesce(source_state->'estimates','[]')||jsonb_build_array(e)) where id='main';
 link_cmd:=jsonb_build_object('operation','LINK_ESTIMATE','request_id',gen_random_uuid(),'rc_no',rc,'expected_revision',1,'estimate_no',eno,'reason','Quotation submitted to surveyor');
 begin perform zukait_reception_command(emp,link_cmd);raise exception 'employee linked estimate'; exception when others then if sqlerrm<>'reception_approval_forbidden' then raise; end if; end;
 a:=zukait_reception_command(sup,link_cmd);qid:=(a->'quotation'->>'id')::uuid;
 if a->'record'->>'revision'<>'2' or a->'record'->>'approval_status'<>'WAITING' then raise exception 'link transition wrong'; end if;
 if (zukait_reception_command(sup,link_cmd)->>'duplicate')::boolean is distinct from true then raise exception 'link retry duplicated'; end if;
 begin perform zukait_reception_command(mgr,link_cmd||jsonb_build_object('request_id',gen_random_uuid(),'rc_no',rc||'-other'));raise exception 'same estimate linked to other RC'; exception when others then if sqlerrm<>'reception_estimate_already_linked' then raise; end if; end;
 c:=jsonb_build_object('operation','RECORD_APPROVAL','request_id',gen_random_uuid(),'rc_no',rc,'expected_revision',2,'quotation_id',qid,'reference','APP-1','approval_date',(now() at time zone 'Asia/Muscat')::date,'approved_amount','120.555','approved_parts',jsonb_build_array(jsonb_build_object('id',item->>'id','qty',1)),'reason','Surveyor approved repair');
 update workshop_receptions set details=details||'{"model":"Corolla"}' where rc_no=rc;
 begin perform zukait_reception_command(sup,c);raise exception 'wrong vehicle approved'; exception when others then if sqlerrm<>'reception_estimate_vehicle_mismatch' then raise; end if; end;
 update workshop_receptions set details=details||'{"model":"Camry"}' where rc_no=rc;
 update workshop_state set data=jsonb_set(data,'{estimates}',coalesce(source_state->'estimates','[]')||jsonb_build_array(e||'{"updatedAt":2}')) where id='main';
 begin perform zukait_reception_command(sup,c);raise exception 'changed quotation approved'; exception when others then if sqlerrm<>'reception_estimate_changed' then raise; end if; end;
 -- Refresh link and approve through the real service-role grants.
 execute 'set local role service_role';
 a:=zukait_reception_command(mgr,link_cmd||jsonb_build_object('request_id',gen_random_uuid(),'expected_revision',2));
 c:=c||jsonb_build_object('expected_revision',3);
 begin perform zukait_reception_command(sup,c||'{"approved_amount":"120.5555"}');raise exception 'four decimals accepted'; exception when others then if sqlerrm<>'reception_invalid_approval' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||'{"reference":""}');raise exception 'empty approval reference accepted'; exception when others then if sqlerrm<>'reception_invalid_approval' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||jsonb_build_object('approval_date',(now() at time zone 'Asia/Muscat')::date+1));raise exception 'future approval accepted'; exception when others then if sqlerrm<>'reception_invalid_approval' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||'{"approval_date":"2026-02-30"}');raise exception 'invalid approval date accepted'; exception when others then if sqlerrm<>'reception_invalid_approval' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||jsonb_build_object('approved_parts',jsonb_build_array(jsonb_build_object('id',item->>'id','qty',3))));raise exception 'excess approved qty accepted'; exception when others then if sqlerrm<>'reception_invalid_approved_parts' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||jsonb_build_object('approved_parts',(c->'approved_parts')||(c->'approved_parts')));raise exception 'duplicate approved items accepted'; exception when others then if sqlerrm<>'reception_invalid_approved_parts' then raise; end if; end;
 begin perform zukait_reception_command(sup,c||'{"reason":{"text":"invalid"}}');raise exception 'non-text reason accepted'; exception when others then if sqlerrm<>'reception_reason_required' then raise; end if; end;
 a:=zukait_reception_command(sup,c);
 if a->'record'->>'approval_status'<>'APPROVED' or a->'record'->>'location'<>'VWC' or a->'record'->>'job_card' is not null then raise exception 'approval created/moved a job'; end if;
 if (a->'approval'->>'approved_amount')::numeric<>120.555 or a->'approval'->'approved_parts'->0->>'qty'<>'1' then raise exception 'amount/quantity changed'; end if;
 if (zukait_reception_command(sup,c)->>'duplicate')::boolean is distinct from true then raise exception 'approval retry duplicated'; end if;
 b:=zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc));
 if (b->'insurance'->>'approval_valid')::boolean is distinct from true then raise exception 'valid approval not recognized'; end if;
 execute 'reset role';
 if (select count(*) from workshop_reception_approvals where rc_no=rc)<>1 then raise exception 'duplicate approval'; end if;
 begin perform zukait_reception_command(sup,c||jsonb_build_object('request_id',gen_random_uuid()));raise exception 'stale approval accepted'; exception when others then if sqlerrm<>'reception_stale_revision' then raise; end if; end;
 update workshop_receptions set details=details||'{"fuel":"Full"}' where rc_no=rc;
 if (zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc))->'insurance'->>'approval_valid')::boolean is distinct from true then raise exception 'observation invalidates approval'; end if;
 update workshop_receptions set details=details||'{"vin":"CORRECTED"}' where rc_no=rc;
 if (zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc))->'insurance'->>'approval_valid')::boolean is distinct from false then raise exception 'vehicle change not flagged'; end if;
 update workshop_receptions set details=details-'vin' where rc_no=rc;
 update workshop_reception_preliminary_parts set items=jsonb_build_array(item||'{"qty":3}') where rc_no=rc;
 if (zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc))->'insurance'->>'approval_valid')::boolean is distinct from false then raise exception 'parts change not flagged'; end if;
 update workshop_reception_preliminary_parts set items=parts where rc_no=rc;
 update workshop_state set data=jsonb_set(data,'{estimates}',coalesce(source_state->'estimates','[]')||jsonb_build_array(e||'{"updatedAt":3}')) where id='main';
 if (zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc))->'insurance'->>'approval_valid')::boolean is distinct from false then raise exception 'estimate change not flagged'; end if;
 update workshop_state set data=jsonb_set(data,'{estimates}',coalesce(source_state->'estimates','[]')||jsonb_build_array(e||'{"updatedAt":2}')) where id='main';
 insert into workshop_reception_access(user_id,granted_by) values(emp,mgr) on conflict(user_id) do update set active=true;
 b:=zukait_reception_command(emp,jsonb_build_object('operation','GET','rc_no',rc));
 if (b->'insurance'->>'can_prepare')::boolean then raise exception 'reception staff can approve'; end if;
 begin perform zukait_reception_command(emp,c);raise exception 'designated staff approved'; exception when others then if sqlerrm<>'reception_approval_forbidden' then raise; end if; end;
 ref_cmd:=jsonb_build_object('operation','REVOKE_APPROVAL','request_id',gen_random_uuid(),'rc_no',rc,'expected_revision',4,'reason','Manager review of approval');
 begin perform zukait_reception_command(sup,ref_cmd);raise exception 'Supervisor revoked'; exception when others then if sqlerrm<>'reception_manager_required' then raise; end if; end;
 a:=zukait_reception_command(mgr,ref_cmd);
 if a->'record'->>'approval_status'<>'WAITING' or a->'record'->>'location'<>'VWC' or (select count(*) from workshop_reception_approvals where rc_no=rc)<>1 then raise exception 'revocation lost history/moved vehicle'; end if;
 if (zukait_reception_command(mgr,jsonb_build_object('operation','GET','rc_no',rc))->'insurance'->>'approval_valid')::boolean is distinct from false then raise exception 'revocation not recognized'; end if;
 c:=c||jsonb_build_object('request_id',gen_random_uuid(),'expected_revision',5);
 perform zukait_reception_command(mgr,c);
 update workshop_receptions set job_card='QA-NO-REAL-JC' where rc_no=rc;
 begin perform zukait_reception_command(mgr,c||jsonb_build_object('request_id',gen_random_uuid(),'expected_revision',6));raise exception 'linked approval accepted'; exception when others then if sqlerrm<>'reception_approval_linked_requires_next_phase' then raise; end if; end;
 update workshop_receptions set job_card=null where rc_no=rc;
 perform zukait_reception_command(mgr,jsonb_build_object('operation','CLOSE','request_id',gen_random_uuid(),'rc_no',rc,'expected_revision',6,'outcome','CANCELLED','reason','Close fixture'));
 begin perform zukait_reception_command(mgr,c||jsonb_build_object('request_id',gen_random_uuid(),'expected_revision',7));raise exception 'closed approval accepted'; exception when others then if sqlerrm<>'reception_case_closed' then raise; end if; end;
 if (select count(*) from workshop_reception_audit where rc_no=rc and operation='RECORD_APPROVAL')<>2 then raise exception 'approval audit mismatch'; end if;
 update workshop_state set data=source_state where id='main';
 if (select revision from workshop_state where id='main')<>source_revision or (select count(*) from workshop_v2_spare_part_state)<>source_parts or (select count(*) from workshop_v2_events)<>source_events then raise exception 'operational data changed'; end if;
 if (select last_value from workshop_reception_no_seq)<>rc_seq or (select is_called from workshop_reception_no_seq)<>rc_called or (select last_value from workshop_v2_estimate_no_seq)<>est_seq or (select is_called from workshop_v2_estimate_no_seq)<>est_called then raise exception 'business sequence consumed'; end if;
end $$;
