-- Rollback-only integration test for replacement-cycle invoice revisions.
begin; do $$ declare pid text:='AUDIT-'||gen_random_uuid()::text; begin insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-list',pid,'SPARE_PART_LISTED',1,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"name":"Audit fixture","qty":1}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-receive1',pid,'SPARE_PART_STATUS_CHANGED',2,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"LISTED","to":"RECEIVED","receivedQty":1}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-verify1',pid,'SPARE_PART_STATUS_CHANGED',3,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"RECEIVED","to":"SUPERVISOR_VERIFIED"}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-invoice1',pid,'SPARE_PART_FINAL_PRICE_RECORDED',1,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"finalPrice":25}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-return',pid,'SPARE_PART_STATUS_CHANGED',4,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"SUPERVISOR_VERIFIED","to":"RETURNED","returnedQty":1,"preReturnSnapshot":{"status":"SUPERVISOR_VERIFIED","receivedQty":1,"purchaseAmount":25,"purchaseAmountRevision":1}}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-enquiry2',pid,'SPARE_PART_STATUS_CHANGED',5,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"RETURNED","to":"ENQUIRY"}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-ordered2',pid,'SPARE_PART_STATUS_CHANGED',6,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"ENQUIRY","to":"ORDERED"}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-receive2',pid,'SPARE_PART_STATUS_CHANGED',7,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"ORDERED","to":"RECEIVED","receivedQty":1}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-verify2',pid,'SPARE_PART_STATUS_CHANGED',8,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"from":"RECEIVED","to":"SUPERVISOR_VERIFIED"}'::jsonb);
insert into public.workshop_v2_events(event_id,entity_id,event_type,revision,server_time,payload) values(pid||'-invoice2',pid,'SPARE_PART_FINAL_PRICE_RECORDED',2,clock_timestamp(),jsonb_build_object('partId',pid,'listNo',pid,'jobCard',pid)||'{"finalPrice":35}'::jsonb);end $$; select 'second_cycle_invoice_accepted_with_increasing_revision' as check_result; rollback;
