import fs from 'node:fs';import vm from 'node:vm';
const src=fs.readFileSync('app/src/main/assets/v2/features/leave/rules.js','utf8');
const ctx={window:{},Date};vm.createContext(ctx);vm.runInContext(src,ctx);const l=ctx.window.zukaitV2.leave;
const full={emp:'E1',date:'2026-09-27',period:'FULL',remark:'Annual'};
const seg=l.segments(full);if(seg.length!==2||(seg[0][1]-seg[0][0])!==5*3600000||(seg[1][1]-seg[1][0])!==4*3600000)throw Error('full duty segments');
if(l.segments({...full,period:'AM'})[0][1]-l.segments({...full,period:'AM'})[0][0]!==5*3600000)throw Error('AM');
if(l.segments({...full,period:'PM'})[0][1]-l.segments({...full,period:'PM'})[0][0]!==4*3600000)throw Error('PM');
if(!l.canManage({id:'E1',role:'Employee'},'E1','Employee'))throw Error('self');
if(!l.canManage({id:'S1',role:'Supervisor'},'E1','Employee'))throw Error('supervisor employee');
if(l.canManage({id:'S1',role:'Supervisor'},'S2','Supervisor'))throw Error('supervisor supervisor');
if(!l.canManage({id:'M1',role:'Manager'},'S1','Supervisor'))throw Error('manager supervisor');
if(l.validate(full,{closedDay:true}).code!=='CLOSED_DAY')throw Error('closed');
const am=l.segments({...full,period:'AM'})[0];
if(l.validate({...full,period:'AM'},{sessions:[{emp:'E1',start:am[0]+60000,end:am[0]+120000}],now:am[1]}).code!=='WORK_CONFLICT')throw Error('work conflict');
if(l.validate({...full,period:'AM'},{leaves:[{emp:'E1',date:full.date,period:'FULL'}]}).code!=='DUPLICATE')throw Error('duplicate');
const built=l.build(full,{actorId:'S1',at:100,id:'L1',auditId:'A1'});if(!built.ok||built.leave.by!=='S1'||built.audit.action!=='ADD')throw Error('build');
const cancelled=l.cancel(built.leave,{actorId:'M1',at:200,auditId:'A2'});if(!cancelled.leave.cancelled||cancelled.audit.action!=='CANCEL'||cancelled.leave.cancelledBy!=='M1')throw Error('cancel');
if(l.overlapMinutes([built.leave],'E1',seg[0][0],seg[1][1])!==540)throw Error('overlap');
if(!l.isOnLeave([built.leave],'E1',seg[0][0]+1)||l.isOnLeave([built.leave],'E1',seg[0][1]+1))throw Error('active split');
console.log('V2 leave parity tests passed');
