plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zukait.timetrack'
    compileSdk 35

    defaultConfig {
        applicationId 'com.zukait.timetrack'
        minSdk 24
        targetSdk 35
        versionCode 62
        versionName 'V99'
    }
}


dependencies {
    implementation "androidx.webkit:webkit:1.17.0"
    implementation "androidx.core:core:1.15.0"
}
