(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.zukaitPaintOrderRules=api})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const key=v=>String(v??'').trim().toUpperCase(),money=v=>Math.round((Number(v)||0)*1000)/1000;
 const active=o=>o&&!o.voided;
 function primaryOrder(orders,no){return (orders||[]).filter(o=>active(o)&&key(o.jobCard)===key(no)&&!o.parentOrderId&&String(o.orderType||'').toUpperCase()!=='ADDITIONAL').sort((a,b)=>Number(a.createdAt||0)-Number(b.createdAt||0)||String(a.id).localeCompare(String(b.id)))[0]||null}
 function validateNewOrders(orders,previous){const known=new Set((previous||[]).map(o=>String(o?.id||'')));for(const o of orders||[]){if(!active(o)||known.has(String(o.id||'')))continue;const primary=primaryOrder(orders,o.jobCard),additional=String(o.orderType||'').toUpperCase()==='ADDITIONAL'||!!o.parentOrderId;if(additional){const parent=(orders||[]).find(p=>active(p)&&String(p.id)===String(o.parentOrderId));if(!parent||parent.parentOrderId||String(parent.orderType||'').toUpperCase()==='ADDITIONAL'||key(parent.jobCard)!==key(o.jobCard)||String(parent.poNumber)!==String(o.parentPoNumber)||!String(o.additionalReason||'').trim())return 'Additional paint order requires the original PO reference and a reason.'}else if(!primary||primary.id!==o.id||(orders||[]).some(p=>active(p)&&key(p.jobCard)===key(o.jobCard)&&!p.parentOrderId&&String(p.orderType||'').toUpperCase()!=='ADDITIONAL'&&p.id!==o.id))return 'A main Paint Purchase Order already exists for this Job Card. Use Additional Paint Order.'}return null}
 function costForJob(orders,no){const all=(orders||[]).filter(o=>o&&key(o.jobCard)===key(no));if(!all.some(o=>o.receivedAt||o.nilPaintPurchase))return null;const rows=all.filter(o=>active(o)&&(o.receivedAt||o.nilPaintPurchase)),lineCost=l=>l.lineTotal!=null&&Number.isFinite(Number(l.lineTotal))?money(l.lineTotal):money(Number(l.quantity||0)*Number(l.pricePerLitre||0));let gross=0,returned=0;for(const o of rows){if(o.nilPaintPurchase)continue;gross+= (o.lines||[]).reduce((n,l)=>n+lineCost(l),0);returned+=(o.returns||[]).filter(r=>r&&!r.voided).reduce((n,r)=>{if(r.value!=null&&Number.isFinite(Number(r.value)))return n+money(r.value);const l=(o.lines||[]).find(l=>l.id===r.lineId);return n+money(l&&Number(l.quantity)>0?lineCost(l)*Number(r.quantity||0)/Number(l.quantity):Number(r.quantity||0)*Number(r.pricePerLitre||0))},0)}const nil=rows.some(o=>o.nilPaintPurchase);return {jobCard:String(no),poNumber:primaryOrder(all,no)?.poNumber||'',orderIds:rows.map(o=>o.id),grossPaintCost:money(gross),returnedPaintValue:money(returned),netPaintCost:money(gross-returned),nilPaintPurchase:nil,paintStatus:nil&&money(gross-returned)===0?'NIL – No Purchase Required':'Costed'}}
 return {primaryOrder,validateNewOrders,costForJob};
});
